# Generated by Django 4.1.1 on 2022-09-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificate_certificate_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate',
        ),
        migrations.AddField(
            model_name='certificate',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='document'),
        ),
    ]
